SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS ordered_menu;
DROP TABLE IF EXISTS menu_img;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS menu;
DROP TABLE IF EXISTS member;

SET FOREIGN_KEY_CHECKS = 1;


